;    Copyright (C) 2012-2018 Joe G.
;
;    This program is free software: you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation, either version 3 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with this program.  If not, see <http://www.gnu.org/licenses/>.
;
;
;
;    Create a bootable image cpm.bin of CP/M with CCPZ
;    Based on original Digital Research source for BDOS
;    CCP is replaced by CCPZ a Z80 version of CP/M CCP
;    Required sources are IPL.MAC, CCP.MAC, ZSDOS.MAC, BIOS.MAC, AVRCPM.LIB, CFGACPM.LIB, ZSDOS.LIB, MEMCFG.LIB
;    Required programs: M80.COM, L80.COM, DDT.COM

XSUB
; get correct configuration

; create IPL.COM
M80 =IPL/M
L80 IPL,IPL/N/E
ERA IPL.REL

; create CCP.COM
M80 =CCP/M
L80 CCP,CCP/N/E
ERA CCP.REL

; create BDOS.COM
M80 =ZSDOS/M
L80 ZSDOS,ZSDOS/N/E
ERA ZSDOS.REL

; create BIOS.COM
M80 =BIOS/M
L80 BIOS,BIOS/N/E
ERA BIOS.REL

; put pieces together
DDT
; fills memory with constant data 0
F100 5C00 0
IIPL.COM
R0000
ICCP.COM
R0080
IZSDOS.COM
R0880
IBIOS.COM
R1680
; go
G0

; create boot file on A:
SAVE 26 A:cpm.bin

; delete temp files
ERA IPL.COM
ERA CCP.COM
ERA ZSDOS.COM
ERA BIOS.COM
